# config/sandbox/public.yaml
name: "client-admin"
namespace: "sandbox"
replicas: 1
container:
  # FIXME: Váriaveis de ambiente não são boas opções para projetos client-side com React e NodeJS
  image: "nossas/bonde-clients:latest"
  command: 
    - "pnpm"
    - "--filter"
    - "admin-client"
    - "start"
  port: 5000
  liveness_probe_path: null
  readiness_probe_path: null
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
service:
  type: "ClusterIP"
  port: 80
  target_port: 5000
ingress:
  enabled: false
labels:
  component: "frontend"
  app: "client-admin"