name: Pulumi (Pull Request)
on:
  - pull_request
jobs:
  preview:
    name: "Preview all stacks"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: [shared, sandbox]

    steps:
      - uses: actions/checkout@v4
      
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: "Install uv"
        uses: astral-sh/setup-uv@v7

      - name: "Install Python dependencies"
        run: uv sync
      
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Preview ${{ matrix.stack }} changes"
        uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: nossas/infra-eks/${{ matrix.stack }}
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}