name: Pulumi (Deploy/Sandbox)
on:
  push:
    branches:
      - main
      - feature/*
      - hotfix/*
    paths-ignore:
      - 'shared/*'
      - 'Pulumi.shared.yaml'
      - 'production/*'
      - 'Pulumi.production.yaml'
      - 'config/production/*'
      - 'config/caddy/caddy-production.json'
jobs:
  deploy:
    name: "Update sandbox environment"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: "Install uv"
        uses: astral-sh/setup-uv@v7

      - name: "Install Python dependencies"
        run: uv sync
      
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Update"
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: nossas/infra-eks/sandbox
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}